"""initial

Revision ID: 1fd566a07e4b
Revises: 
Create Date: 2026-08-27 12:45:05.368919

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1fd566a07e4b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('mandis',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('agmarknet_market', sa.String(length=120), nullable=False),
    sa.Column('agmarknet_state', sa.String(length=64), nullable=False),
    sa.Column('agmarknet_district', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocols',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.CheckConstraint("kind IN ('crop', 'pharma')", name='ck_protocols_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_ops',
    sa.Column('op_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('client_seq', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('batch.create', 'batch.update', 'reading.append')", name='ck_sync_ops_kind'),
    sa.CheckConstraint("status IN ('applied', 'duplicate', 'rejected')", name='ck_sync_ops_status'),
    sa.PrimaryKeyConstraint('op_id')
    )
    with op.batch_alter_table('sync_ops', schema=None) as batch_op:
        batch_op.create_index('ix_sync_ops_device_seq', ['device_id', 'client_seq'], unique=False)

    op.create_table('batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_id', sa.String(length=36), nullable=False),
    sa.Column('crop', sa.String(length=32), nullable=False),
    sa.Column('protocol_id', sa.String(length=64), nullable=False),
    sa.Column('qty_kg', sa.Float(), nullable=False),
    sa.Column('harvested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=True),
    sa.Column('origin_lon', sa.Float(), nullable=True),
    sa.Column('origin_geohash', sa.String(length=12), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('client_seq', sa.Integer(), nullable=False),
    sa.Column('client_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('open', 'sold', 'spoiled', 'discarded')", name='ck_batches_status'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index('ix_batches_farmer_id', ['farmer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_protocol_id'), ['protocol_id'], unique=False)

    op.create_table('mandi_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mandi_id', sa.String(length=64), nullable=False),
    sa.Column('commodity', sa.String(length=64), nullable=False),
    sa.Column('variety', sa.String(length=64), nullable=True),
    sa.Column('modal_price', sa.Float(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('arrival_qty', sa.Float(), nullable=True),
    sa.Column('reported_on', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['mandi_id'], ['mandis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandi_id', 'commodity', 'reported_on', name='uq_mandi_prices_mandi_commodity_day')
    )
    with op.batch_alter_table('mandi_prices', schema=None) as batch_op:
        batch_op.create_index('ix_mandi_prices_commodity_reported_on', ['commodity', 'reported_on'], unique=False)

    op.create_table('pass_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=8), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint("event IN ('view', 'verify')", name='ck_pass_events_event'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pass_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pass_events_batch_id'), ['batch_id'], unique=False)

    op.create_table('readings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('geohash', sa.String(length=12), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('client_seq', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'sim', 'ble')", name='ck_readings_source'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'seq', name='uq_readings_batch_seq')
    )
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readings_batch_id'), ['batch_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('ranked_json', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_batch_id'), ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_batch_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readings_batch_id'))

    op.drop_table('readings')
    with op.batch_alter_table('pass_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pass_events_batch_id'))

    op.drop_table('pass_events')
    with op.batch_alter_table('mandi_prices', schema=None) as batch_op:
        batch_op.drop_index('ix_mandi_prices_commodity_reported_on')

    op.drop_table('mandi_prices')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_protocol_id'))
        batch_op.drop_index('ix_batches_farmer_id')

    op.drop_table('batches')
    with op.batch_alter_table('sync_ops', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_ops_device_seq')

    op.drop_table('sync_ops')
    op.drop_table('protocols')
    op.drop_table('mandis')
    op.drop_table('farmers')
    # ### end Alembic commands ###
